### ISSUE TITLE
Load and render awesome-data topics as data literate docs

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-literate#13]
When I have a set of content in a separate github repo I want to load and render that as part of my app so i can manage content separately but integrate it into my site

A good sample of data to work with would be https://github.com/datasets/awesome-data and have it look like https://datahub.io/collections

## Acceptance

* [x] Content at https://github.com/datasets/awesome-data  shows up at e.g. `/topics/{id}` (~~with README at index page ...~~) **DONE see e.g. http://data-literate.datopian.com/topics. Index page is crude atm but serviceable for now**
* [x] Pages are rendered as data literate docs **DONE. See e.g. http://data-literate.datopian.com/topics/climate-change**

BONUS features

* [ ] Can reference datahub.io datasets and they expand into a little summary with a link
* [ ] Nicer index page - like https://datahub.io/collections

## Tasks

* [x] Load list of files (and their content) from github
  * [x] Set up graphql
  * [x] Set up authentication to github **DONE: bearer with personal access token**
  * [x] Find a graphql query for loading this info from github **DONE: https://gist.github.com/MichaelCurrin/6777b91e6374cdb5662b64b8249070ea**
* [x] render each page as data literate doc
* [x] create an index page
